Repository IRECIPE/IRecipe-Server, pull requests merged in 2024-01, with the labels that each got.

#10 1️⃣ [INIT] API Response 통일
  .gradle/8.5/checksums/checksums.lock
  .gradle/8.5/checksums/md5-checksums.bin
  .gradle/8.5/checksums/sha1-checksums.bin
  .gradle/8.5/dependencies-accessors/dependencies-accessors.lock
  .gradle/8.5/dependencies-accessors/gc.properties
  .gradle/8.5/executionHistory/executionHistory.bin
  .gradle/8.5/executionHistory/executionHistory.lock
  .gradle/8.5/fileChanges/last-build.bin
  .gradle/8.5/fileHashes/fileHashes.bin
  .gradle/8.5/fileHashes/fileHashes.lock
  .gradle/8.5/fileHashes/resourceHashesCache.bin
  .gradle/8.5/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .gradle/vcs-1/gc.properties
  .idea/IRecipe-Server.iml
  .idea/gradle.xml
  .idea/modules/IRECIPE_Server.main.iml
  .idea/vcs.xml
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/umc/IRECIPE_Server/apiPayLoad/ApiResponse.java
  src/main/java/umc/IRECIPE_Server/apiPayLoad/code/BaseCode.java
  src/main/java/umc/IRECIPE_Server/apiPayLoad/code/BaseErrorCode.java
  src/main/java/umc/IRECIPE_Server/apiPayLoad/code/ErrorReasonDTO.java
  src/main/java/umc/IRECIPE_Server/apiPayLoad/code/ReasonDTO.java
  src/main/java/umc/IRECIPE_Server/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/IRECIPE_Server/apiPayLoad/code/status/SuccessStatus.java
  src/main/java/umc/IRECIPE_Server/apiPayLoad/exception/ExceptionAdvice.java
  src/main/java/umc/IRECIPE_Server/apiPayLoad/exception/GeneralException.java
Labels: :heavy_check_mark: check

#12 에러코드 추가 및 테스트 완료
  .gradle/8.5/checksums/checksums.lock
  .gradle/8.5/dependencies-accessors/dependencies-accessors.lock
  .gradle/8.5/dependencies-accessors/gc.properties
  .gradle/8.5/executionHistory/executionHistory.bin
  .gradle/8.5/executionHistory/executionHistory.lock
  .gradle/8.5/fileChanges/last-build.bin
  .gradle/8.5/fileHashes/fileHashes.bin
  .gradle/8.5/fileHashes/fileHashes.lock
  .gradle/8.5/fileHashes/resourceHashesCache.bin
  .gradle/8.5/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .gradle/vcs-1/gc.properties
  .idea/misc.xml
  .idea/modules/IRECIPE_Server.main.iml
  build/resources/main/application-local.yml
  build/tmp/compileJava/compileTransaction/stash-dir/Member$MemberBuilder.class.uniqueId16
  build/tmp/compileJava/compileTransaction/stash-dir/Member.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/MemberAgree$MemberAgreeBuilder.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/MemberAgree.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/MemberAllergy$MemberAllergyBuilder.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/MemberAllergy.class.uniqueId15
  build/tmp/compileJava/compileTransaction/stash-dir/Post$PostBuilder.class.uniqueId6
  build/tmp/compileJava/compileTransaction/stash-dir/Post.class.uniqueId14
  build/tmp/compileJava/compileTransaction/stash-dir/PostImage$PostImageBuilder.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/PostImage.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/Refri$RefriBuilder.class.uniqueId17
  build/tmp/compileJava/compileTransaction/stash-dir/Refri.class.uniqueId7
  build/tmp/compileJava/compileTransaction/stash-dir/Review$ReviewBuilder.class.uniqueId12
  build/tmp/compileJava/compileTransaction/stash-dir/Review.class.uniqueId10
  build/tmp/compileJava/compileTransaction/stash-dir/ReviewComment$ReviewCommentBuilder.class.uniqueId9
  build/tmp/compileJava/compileTransaction/stash-dir/ReviewComment.class.uniqueId8
  build/tmp/compileJava/compileTransaction/stash-dir/ReviewImage$ReviewImageBuilder.class.uniqueId11
  build/tmp/compileJava/compileTransaction/stash-dir/ReviewImage.class.uniqueId13
  build/tmp/compileJava/compileTransaction/stash-dir/TempQueryServiceImpl.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/umc/IRECIPE_Server/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/IRECIPE_Server/apiPayLoad/exception/handler/TempHandler.java
  src/main/java/umc/IRECIPE_Server/converter/TempConverter.java
  src/main/java/umc/IRECIPE_Server/service/TempQueryService.java
  src/main/java/umc/IRECIPE_Server/service/TempQueryServiceImpl.java
  src/main/java/umc/IRECIPE_Server/web/controller/TempRestController.java
  src/main/java/umc/IRECIPE_Server/web/dto/TempResponse.java
Labels: :sparkles: feature

#14 [check]: gitignore 수정
  .gitignore
  .idea/misc.xml
Labels: :heavy_check_mark: check

#16 👷 [CI] CI/CD 파이프라인 구현
  .ebextensions_dev/00-makeFiles.config
  .ebextensions_dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .idea/compiler.xml
  .platform/nginx.conf
  Procfile
  build.gradle
  src/main/java/umc/IRECIPE_Server/controller/HealthCheckController.java
Labels: :sparkles: feature, :construction_worker: ci

#28 🐛 [FIX] CI/CD health check 에러 해결
  src/main/java/umc/IRECIPE_Server/config/SecurityConfig.java
Labels: :bug: bug, :construction_worker: ci

#32 login 구현, swagger 설정
  build.gradle
  build/classes/java/main/umc/IRECIPE_Server/domain/mapping/Member$MemberBuilder.class
  build/classes/java/main/umc/IRECIPE_Server/domain/mapping/Member.class
  build/resources/main/application-local.yml
  src/main/java/umc/IRECIPE_Server/config/SecurityConfig.java
  src/main/java/umc/IRECIPE_Server/config/SwaggerConfig.java
  src/main/java/umc/IRECIPE_Server/domain/mapping/Member.java
  src/main/java/umc/IRECIPE_Server/jwt/JwtAuthenticationFilter.java
  src/main/java/umc/IRECIPE_Server/jwt/JwtTokenProvider.java
  src/main/java/umc/IRECIPE_Server/repository/MemberRepository.java
  src/main/java/umc/IRECIPE_Server/service/CustomUserDetailsService.java
  src/main/java/umc/IRECIPE_Server/service/MemberService.java
  src/main/java/umc/IRECIPE_Server/web/controller/MemberController.java
  src/main/java/umc/IRECIPE_Server/web/dto/MemberLoginRequestDTO.java
  src/main/java/umc/IRECIPE_Server/web/dto/TokenDTO.java
  src/main/resources/application-local.yml
Labels: :sparkles: feature

#35 Feat/get post
  src/main/java/umc/IRECIPE_Server/controller/MemberController.java
  src/main/java/umc/IRECIPE_Server/controller/PostController.java
  src/main/java/umc/IRECIPE_Server/dto/MemberLoginRequestDTO.java
  src/main/java/umc/IRECIPE_Server/dto/PostRequestDTO.java
  src/main/java/umc/IRECIPE_Server/dto/PostResponseDTO.java
  src/main/java/umc/IRECIPE_Server/dto/TokenDTO.java
  src/main/java/umc/IRECIPE_Server/entity/Member.java
  src/main/java/umc/IRECIPE_Server/entity/Post.java
  src/main/java/umc/IRECIPE_Server/jwt/JwtTokenProvider.java
  src/main/java/umc/IRECIPE_Server/repository/PostImageRepository.java
  src/main/java/umc/IRECIPE_Server/service/MemberService.java
  src/main/java/umc/IRECIPE_Server/service/PostService.java
Labels: :sparkles: feature

#36 ✨ [FEAT] AI Chatbot CRUD
  build.gradle
  build/classes/java/main/umc/IRECIPE_Server/IRecipeServerApplication.class
  build/classes/java/main/umc/IRECIPE_Server/apiPayLoad/ApiResponse.class
  build/classes/java/main/umc/IRECIPE_Server/apiPayLoad/code/BaseCode.class
  build/classes/java/main/umc/IRECIPE_Server/apiPayLoad/code/BaseErrorCode.class
  build/classes/java/main/umc/IRECIPE_Server/apiPayLoad/code/ErrorReasonDTO$ErrorReasonDTOBuilder.class
  build/classes/java/main/umc/IRECIPE_Server/apiPayLoad/code/ErrorReasonDTO.class
  build/classes/java/main/umc/IRECIPE_Server/apiPayLoad/code/ReasonDTO$ReasonDTOBuilder.class
  build/classes/java/main/umc/IRECIPE_Server/apiPayLoad/code/ReasonDTO.class
  build/classes/java/main/umc/IRECIPE_Server/apiPayLoad/code/status/ErrorStatus.class
  build/classes/java/main/umc/IRECIPE_Server/apiPayLoad/code/status/SuccessStatus.class
  build/classes/java/main/umc/IRECIPE_Server/apiPayLoad/exception/ExceptionAdvice.class
  build/classes/java/main/umc/IRECIPE_Server/apiPayLoad/exception/GeneralException.class
  build/classes/java/main/umc/IRECIPE_Server/apiPayLoad/exception/handler/TempHandler.class
  build/classes/java/main/umc/IRECIPE_Server/common/BaseEntity.class
  build/classes/java/main/umc/IRECIPE_Server/controller/HealthCheckController.class
  build/classes/java/main/umc/IRECIPE_Server/converter/TempConverter.class
  build/classes/java/main/umc/IRECIPE_Server/service/TempQueryService.class
  build/classes/java/main/umc/IRECIPE_Server/service/TempQueryServiceImpl.class
  build/resources/main/application-local.yml
  build/resources/main/application.yml
  src/main/java/umc/IRECIPE_Server/config/ChatGptConfig.java
  src/main/java/umc/IRECIPE_Server/controller/ChatGptController.java
  src/main/java/umc/IRECIPE_Server/controller/MemberController.java
  src/main/java/umc/IRECIPE_Server/controller/PostController.java
  src/main/java/umc/IRECIPE_Server/converter/ChatGptConverter.java
  src/main/java/umc/IRECIPE_Server/dto/request/ChatGptMessageDto.java
  src/main/java/umc/IRECIPE_Server/dto/request/ChatGptRecipeSaveRequestDTO.java
  src/main/java/umc/IRECIPE_Server/dto/request/ChatGptRequestDTO.java
  src/main/java/umc/IRECIPE_Server/dto/request/MemberLoginRequestDTO.java
  src/main/java/umc/IRECIPE_Server/dto/request/PostRequestDTO.java
  src/main/java/umc/IRECIPE_Server/dto/request/UserChatGptRequestDTO.java
  src/main/java/umc/IRECIPE_Server/dto/response/ChatGptButtonResponseDTO.java
  src/main/java/umc/IRECIPE_Server/dto/response/ChatGptResponseDTO.java
  src/main/java/umc/IRECIPE_Server/dto/response/PostResponseDTO.java
  src/main/java/umc/IRECIPE_Server/dto/response/UserChatGptResponseDTO.java
  src/main/java/umc/IRECIPE_Server/entity/Ingredient.java
  src/main/java/umc/IRECIPE_Server/entity/Member.java
  src/main/java/umc/IRECIPE_Server/entity/StoredRecipe.java
  src/main/java/umc/IRECIPE_Server/repository/IngredientRepository.java
  src/main/java/umc/IRECIPE_Server/repository/MemberRepository.java
  src/main/java/umc/IRECIPE_Server/repository/StoredRecipeRepository.java
  src/main/java/umc/IRECIPE_Server/service/ChatGptService.java
  src/main/java/umc/IRECIPE_Server/service/ChatGptServiceImpl.java
  src/main/java/umc/IRECIPE_Server/service/PostService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: :sparkles: feature

#39 Feat/3: 회원가입, 로그인 구현 및 jwt 토큰 처리
  build.gradle
  build/classes/java/main/umc/IRECIPE_Server/apiPayLoad/code/status/ErrorStatus.class
  build/resources/main/application-local.yml
  src/main/java/umc/IRECIPE_Server/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/IRECIPE_Server/apiPayLoad/exception/handler/AllergyHandler.java
  src/main/java/umc/IRECIPE_Server/common/enums/Age.java
  src/main/java/umc/IRECIPE_Server/common/enums/Role.java
  src/main/java/umc/IRECIPE_Server/config/MultipartConfig.java
  src/main/java/umc/IRECIPE_Server/config/SecurityConfig.java
  src/main/java/umc/IRECIPE_Server/controller/ChatGptController.java
  src/main/java/umc/IRECIPE_Server/controller/MemberController.java
  src/main/java/umc/IRECIPE_Server/converter/MemberAllergyConverter.java
  src/main/java/umc/IRECIPE_Server/converter/MemberConverter.java
  src/main/java/umc/IRECIPE_Server/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/umc/IRECIPE_Server/dto/MemberSignupRequestDto.java
  src/main/java/umc/IRECIPE_Server/dto/MemberSignupResponseDto.java
  src/main/java/umc/IRECIPE_Server/dto/TokenDTO.java
  src/main/java/umc/IRECIPE_Server/dto/request/MemberLoginRequestDTO.java
  src/main/java/umc/IRECIPE_Server/entity/Ingredient.java
  src/main/java/umc/IRECIPE_Server/entity/Member.java
  src/main/java/umc/IRECIPE_Server/entity/RefreshToken.java
  src/main/java/umc/IRECIPE_Server/jwt/JwtAuthenticationFilter.java
  src/main/java/umc/IRECIPE_Server/jwt/JwtProvider.java
  src/main/java/umc/IRECIPE_Server/repository/MemberRepository.java
  src/main/java/umc/IRECIPE_Server/repository/TokenRepository.java
  src/main/java/umc/IRECIPE_Server/service/ChatGptService.java
  src/main/java/umc/IRECIPE_Server/service/ChatGptServiceImpl.java
  src/main/java/umc/IRECIPE_Server/service/CustomUserDetailsService.java
  src/main/java/umc/IRECIPE_Server/service/MemberService.java
  src/main/java/umc/IRECIPE_Server/service/PostService.java
  src/main/resources/application-local.yml
Labels: :sparkles: feature

#40 [FEAT] 냉장고 CRUD 기능 구현
  build/classes/java/main/umc/IRECIPE_Server/apiPayLoad/code/status/ErrorStatus.class
  build/classes/java/main/umc/IRECIPE_Server/apiPayLoad/exception/handler/IngredientHandler.class
  build/classes/java/main/umc/IRECIPE_Server/converter/IngredientConverter.class
  build/classes/java/main/umc/IRECIPE_Server/repository/IngredientRepository.class
  build/classes/java/main/umc/IRECIPE_Server/service/ingredientService/IngredientCommandService.class
  build/classes/java/main/umc/IRECIPE_Server/service/ingredientService/IngredientCommandServiceImpl.class
  build/classes/java/main/umc/IRECIPE_Server/service/ingredientService/IngredientQueryService.class
  build/classes/java/main/umc/IRECIPE_Server/service/ingredientService/IngredientQueryServiceImpl.class
  build/classes/java/main/umc/IRECIPE_Server/web/dto/IngredientResponse$addResultDTO$addResultDTOBuilder.class
  build/classes/java/main/umc/IRECIPE_Server/web/dto/IngredientResponse$addResultDTO.class
  build/classes/java/main/umc/IRECIPE_Server/web/dto/IngredientResponse$deleteResultDTO$deleteResultDTOBuilder.class
  build/classes/java/main/umc/IRECIPE_Server/web/dto/IngredientResponse$deleteResultDTO.class
  build/classes/java/main/umc/IRECIPE_Server/web/dto/IngredientResponse$findOneResultDTO$findOneResultDTOBuilder.class
  build/classes/java/main/umc/IRECIPE_Server/web/dto/IngredientResponse$findOneResultDTO.class
  build/classes/java/main/umc/IRECIPE_Server/web/dto/IngredientResponse.class
  build/resources/main/application-local.yml
  gradlew
  src/main/java/umc/IRECIPE_Server/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/IRECIPE_Server/apiPayLoad/exception/handler/IngredientHandler.java
  src/main/java/umc/IRECIPE_Server/controller/IngredientController.java
  src/main/java/umc/IRECIPE_Server/converter/IngredientConverter.java
  src/main/java/umc/IRECIPE_Server/dto/IngredientRequest.java
  src/main/java/umc/IRECIPE_Server/dto/IngredientResponse.java
  src/main/java/umc/IRECIPE_Server/entity/Allergy.java
  src/main/java/umc/IRECIPE_Server/entity/Ingredient.java
  src/main/java/umc/IRECIPE_Server/entity/MemberLikes.java
  src/main/java/umc/IRECIPE_Server/repository/IngredientRepository.java
  src/main/java/umc/IRECIPE_Server/repository/MemberRepository.java
  src/main/java/umc/IRECIPE_Server/service/ingredientService/IngredientCommandService.java
  src/main/java/umc/IRECIPE_Server/service/ingredientService/IngredientCommandServiceImpl.java
  src/main/java/umc/IRECIPE_Server/service/ingredientService/IngredientQueryService.java
  src/main/java/umc/IRECIPE_Server/service/ingredientService/IngredientQueryServiceImpl.java
  src/main/resources/application-local.yml
Labels: :sparkles: feature

#41 [FEAT] 게시글 수정, 삭제 구현
  .gitignore
  build.gradle
  src/main/java/umc/IRECIPE_Server/common/MultipartJackson2HttpMessageConverter.java
  src/main/java/umc/IRECIPE_Server/controller/PostController.java
  src/main/java/umc/IRECIPE_Server/converter/PostConverter.java
  src/main/java/umc/IRECIPE_Server/dto/request/PostRequestDTO.java
  src/main/java/umc/IRECIPE_Server/dto/response/PostResponseDTO.java
  src/main/java/umc/IRECIPE_Server/entity/Member.java
  src/main/java/umc/IRECIPE_Server/entity/Post.java
  src/main/java/umc/IRECIPE_Server/entity/PostImage.java
  src/main/java/umc/IRECIPE_Server/repository/MemberRepository.java
  src/main/java/umc/IRECIPE_Server/repository/PostImageRepository.java
  src/main/java/umc/IRECIPE_Server/repository/PostRepository.java
  src/main/java/umc/IRECIPE_Server/service/PostService.java
Labels: :sparkles: feature

#44 Feat/3: 로그인 수정
  build/classes/java/main/umc/IRECIPE_Server/apiPayLoad/code/status/ErrorStatus.class
  build/classes/java/main/umc/IRECIPE_Server/repository/IngredientRepository.class
  build/resources/main/application-local.yml
  src/main/java/umc/IRECIPE_Server/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/IRECIPE_Server/controller/MemberController.java
  src/main/java/umc/IRECIPE_Server/converter/MemberConverter.java
  src/main/java/umc/IRECIPE_Server/dto/MemberLoginRequestDto.java
  src/main/java/umc/IRECIPE_Server/entity/Member.java
  src/main/java/umc/IRECIPE_Server/service/MemberService.java
  src/main/resources/application-local.yml
Labels: :recycle: refactor
