Repository IRECIPE/IRecipe-Server, pull requests merged in 2024-02, with the labels that each got.

#48 Feat/com
  src/main/java/umc/IRECIPE_Server/common/S3/S3Service.java
  src/main/java/umc/IRECIPE_Server/common/enums/Category.java
  src/main/java/umc/IRECIPE_Server/controller/PostController.java
  src/main/java/umc/IRECIPE_Server/converter/PostConverter.java
  src/main/java/umc/IRECIPE_Server/dto/request/PostRequestDTO.java
  src/main/java/umc/IRECIPE_Server/dto/response/PostResponseDTO.java
  src/main/java/umc/IRECIPE_Server/entity/Post.java
  src/main/java/umc/IRECIPE_Server/repository/PostImageRepository.java
  src/main/java/umc/IRECIPE_Server/repository/PostRepository.java
  src/main/java/umc/IRECIPE_Server/service/PostService.java
  src/main/java/umc/IRECIPE_Server/service/TestData.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: :recycle: refactor

#52 Feat/45: 프로필 수정 api 완료
  build/classes/java/main/umc/IRECIPE_Server/converter/IngredientConverter.class
  build/classes/java/main/umc/IRECIPE_Server/service/ingredientService/IngredientQueryServiceImpl.class
  build/classes/java/main/umc/IRECIPE_Server/web/dto/IngredientResponse$addResultDTO$addResultDTOBuilder.class
  build/classes/java/main/umc/IRECIPE_Server/web/dto/IngredientResponse$addResultDTO.class
  build/classes/java/main/umc/IRECIPE_Server/web/dto/IngredientResponse$deleteResultDTO$deleteResultDTOBuilder.class
  build/classes/java/main/umc/IRECIPE_Server/web/dto/IngredientResponse$deleteResultDTO.class
  build/classes/java/main/umc/IRECIPE_Server/web/dto/IngredientResponse$findOneResultDTO$findOneResultDTOBuilder.class
  build/classes/java/main/umc/IRECIPE_Server/web/dto/IngredientResponse$findOneResultDTO.class
  build/classes/java/main/umc/IRECIPE_Server/web/dto/IngredientResponse.class
  src/main/java/umc/IRECIPE_Server/apiPayLoad/exception/handler/MemberHandler.java
  src/main/java/umc/IRECIPE_Server/controller/IngredientController.java
  src/main/java/umc/IRECIPE_Server/controller/MemberController.java
  src/main/java/umc/IRECIPE_Server/converter/IngredientConverter.java
  src/main/java/umc/IRECIPE_Server/converter/MemberConverter.java
  src/main/java/umc/IRECIPE_Server/dto/IngredientResponse.java
  src/main/java/umc/IRECIPE_Server/dto/MemberRequest.java
  src/main/java/umc/IRECIPE_Server/dto/MemberResponse.java
  src/main/java/umc/IRECIPE_Server/dto/MemberSignupRequestDto.java
  src/main/java/umc/IRECIPE_Server/dto/MemberSignupResponseDto.java
  src/main/java/umc/IRECIPE_Server/entity/Member.java
  src/main/java/umc/IRECIPE_Server/jwt/JwtProvider.java
  src/main/java/umc/IRECIPE_Server/repository/AllergyRepository.java
  src/main/java/umc/IRECIPE_Server/repository/MemberAllergyRepository.java
  src/main/java/umc/IRECIPE_Server/repository/MemberRepository.java
  src/main/java/umc/IRECIPE_Server/service/MemberService.java
  src/main/resources/application-dev.yml
Labels: :sparkles: feature

#57 Fix/com 게시글 기능 수정
  src/main/java/umc/IRECIPE_Server/common/S3/S3Service.java
  src/main/java/umc/IRECIPE_Server/controller/MemberController.java
  src/main/java/umc/IRECIPE_Server/controller/PostController.java
  src/main/java/umc/IRECIPE_Server/converter/MemberConverter.java
  src/main/java/umc/IRECIPE_Server/converter/PostConverter.java
  src/main/java/umc/IRECIPE_Server/dto/request/PostRequestDTO.java
  src/main/java/umc/IRECIPE_Server/dto/response/PostResponseDTO.java
  src/main/java/umc/IRECIPE_Server/entity/Member.java
  src/main/java/umc/IRECIPE_Server/entity/Post.java
  src/main/java/umc/IRECIPE_Server/entity/PostImage.java
  src/main/java/umc/IRECIPE_Server/repository/PostImageRepository.java
  src/main/java/umc/IRECIPE_Server/service/ChatGptServiceImpl.java
  src/main/java/umc/IRECIPE_Server/service/PostService.java
Labels: :recycle: refactor

#61 Refactor/53: 회원가입시 필요한 어노테이션 생성
  src/main/java/umc/IRECIPE_Server/controller/MemberController.java
  src/main/java/umc/IRECIPE_Server/dto/MemberRequest.java
  src/main/java/umc/IRECIPE_Server/repository/MemberRepository.java
  src/main/java/umc/IRECIPE_Server/service/MemberService.java
  src/main/java/umc/IRECIPE_Server/validation/annotation/ExistAllergies.java
  src/main/java/umc/IRECIPE_Server/validation/annotation/ExistNickname.java
  src/main/java/umc/IRECIPE_Server/validation/validator/AllergiesExistValidator.java
  src/main/java/umc/IRECIPE_Server/validation/validator/NicknameExistValidator.java
Labels: :recycle: refactor

#62 ✨ [FEAT] 커뮤니티 게시글 후기 기능 구현
  src/main/java/umc/IRECIPE_Server/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/IRECIPE_Server/common/S3/S3Service.java
  src/main/java/umc/IRECIPE_Server/controller/ChatGptController.java
  src/main/java/umc/IRECIPE_Server/controller/PostController.java
  src/main/java/umc/IRECIPE_Server/controller/ReviewController.java
  src/main/java/umc/IRECIPE_Server/converter/ReviewConverter.java
  src/main/java/umc/IRECIPE_Server/dto/request/ChatGptRecipeSaveRequestDTO.java
  src/main/java/umc/IRECIPE_Server/dto/request/ReviewRequestDTO.java
  src/main/java/umc/IRECIPE_Server/dto/request/UserChatGptRequestDTO.java
  src/main/java/umc/IRECIPE_Server/dto/response/ChatGptButtonResponseDTO.java
  src/main/java/umc/IRECIPE_Server/dto/response/ReviewResponseDTO.java
  src/main/java/umc/IRECIPE_Server/dto/response/UserChatGptResponseDTO.java
  src/main/java/umc/IRECIPE_Server/entity/Member.java
  src/main/java/umc/IRECIPE_Server/entity/Review.java
  src/main/java/umc/IRECIPE_Server/repository/IngredientRepository.java
  src/main/java/umc/IRECIPE_Server/repository/ReviewRepository.java
  src/main/java/umc/IRECIPE_Server/service/PostService.java
  src/main/java/umc/IRECIPE_Server/service/ReviewService.java
  src/main/java/umc/IRECIPE_Server/service/ReviewServiceImpl.java
Labels: :sparkles: feature

#64 ✨ [FEAT] ChatpGPT API 요구사항 명세서 변경 사항 적용
  .gitignore
  src/main/java/umc/IRECIPE_Server/controller/ChatGptController.java
  src/main/java/umc/IRECIPE_Server/converter/ChatGptConverter.java
  src/main/java/umc/IRECIPE_Server/dto/request/DislikedFoodRequestDTO.java
  src/main/java/umc/IRECIPE_Server/dto/response/ChatGptButtonResponseDTO.java
  src/main/java/umc/IRECIPE_Server/entity/DislikedFood.java
  src/main/java/umc/IRECIPE_Server/entity/Member.java
  src/main/java/umc/IRECIPE_Server/repository/DislikedFoodRepository.java
  src/main/java/umc/IRECIPE_Server/repository/IngredientRepository.java
  src/main/java/umc/IRECIPE_Server/service/ChatGptService.java
  src/main/java/umc/IRECIPE_Server/service/ChatGptServiceImpl.java
  src/main/java/umc/IRECIPE_Server/service/PostService.java
  src/main/resources/application.yml
Labels: :recycle: refactor, :sparkles: feature

#67 ✨ [FEAT] 커뮤니티 게시글 Qna 기능 구현
  build.gradle
  src/main/generated/umc/IRECIPE_Server/common/QBaseEntity.java
  src/main/generated/umc/IRECIPE_Server/entity/QAllergy.java
  src/main/generated/umc/IRECIPE_Server/entity/QIngredient.java
  src/main/generated/umc/IRECIPE_Server/entity/QMember.java
  src/main/generated/umc/IRECIPE_Server/entity/QMemberAllergy.java
  src/main/generated/umc/IRECIPE_Server/entity/QMemberLikes.java
  src/main/generated/umc/IRECIPE_Server/entity/QPost.java
  src/main/generated/umc/IRECIPE_Server/entity/QQna.java
  src/main/generated/umc/IRECIPE_Server/entity/QRefreshToken.java
  src/main/generated/umc/IRECIPE_Server/entity/QReview.java
  src/main/generated/umc/IRECIPE_Server/entity/QStoredRecipe.java
  src/main/java/umc/IRECIPE_Server/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/IRECIPE_Server/config/QuerydslConfig.java
  src/main/java/umc/IRECIPE_Server/controller/QnaController.java
  src/main/java/umc/IRECIPE_Server/converter/QnaConverter.java
  src/main/java/umc/IRECIPE_Server/dto/request/QnaRequestDTO.java
  src/main/java/umc/IRECIPE_Server/dto/response/QnaResponseDTO.java
  src/main/java/umc/IRECIPE_Server/entity/Answer.java
  src/main/java/umc/IRECIPE_Server/entity/Member.java
  src/main/java/umc/IRECIPE_Server/entity/Post.java
  src/main/java/umc/IRECIPE_Server/entity/Qna.java
  src/main/java/umc/IRECIPE_Server/entity/Query.java
  src/main/java/umc/IRECIPE_Server/repository/AnswerRepository.java
  src/main/java/umc/IRECIPE_Server/repository/QnaCustomRepository.java
  src/main/java/umc/IRECIPE_Server/repository/QnaRepository.java
  src/main/java/umc/IRECIPE_Server/repository/QuestionsRepository.java
  src/main/java/umc/IRECIPE_Server/service/QnaService.java
  src/main/java/umc/IRECIPE_Server/service/QnaServiceImpl.java
Labels: :sparkles: feature

#81 ♻️ [REFACTOR] access token 유효시간 변경
  src/main/java/umc/IRECIPE_Server/jwt/JwtProvider.java
Labels: :recycle: refactor

#82 [DOCS] 커뮤니티, 리뷰, QNA API 스웨거 설명 추가
  src/main/java/umc/IRECIPE_Server/config/SwaggerConfig.java
  src/main/java/umc/IRECIPE_Server/controller/PostController.java
  src/main/java/umc/IRECIPE_Server/controller/QnaController.java
  src/main/java/umc/IRECIPE_Server/controller/ReviewController.java
  src/main/java/umc/IRECIPE_Server/converter/PostConverter.java
  src/main/java/umc/IRECIPE_Server/dto/request/PostRequestDTO.java
  src/main/java/umc/IRECIPE_Server/dto/request/QnaRequestDTO.java
  src/main/java/umc/IRECIPE_Server/dto/request/ReviewRequestDTO.java
  src/main/java/umc/IRECIPE_Server/dto/response/PostResponseDTO.java
  src/main/java/umc/IRECIPE_Server/dto/response/QnaResponseDTO.java
  src/main/java/umc/IRECIPE_Server/dto/response/ReviewResponseDTO.java
  src/main/java/umc/IRECIPE_Server/service/PostService.java
Labels: :memo: docs

#86 ♻️ [REFACTOR] 고유아이디 validation 생성
  src/main/java/umc/IRECIPE_Server/dto/MemberRequest.java
  src/main/java/umc/IRECIPE_Server/repository/MemberRepository.java
  src/main/java/umc/IRECIPE_Server/service/MemberService.java
  src/main/java/umc/IRECIPE_Server/validation/annotation/ExistPersonalId.java
  src/main/java/umc/IRECIPE_Server/validation/validator/PersonalIdExistValidator.java
Labels: :recycle: refactor

#87 [FIX] 게시글 관심 정보 추가
  src/main/java/umc/IRECIPE_Server/controller/PostController.java
  src/main/java/umc/IRECIPE_Server/converter/PostConverter.java
  src/main/java/umc/IRECIPE_Server/dto/request/PostRequestDTO.java
  src/main/java/umc/IRECIPE_Server/dto/response/PostResponseDTO.java
  src/main/java/umc/IRECIPE_Server/repository/MemberLikesRepository.java
  src/main/java/umc/IRECIPE_Server/service/PostService.java
Labels: :sparkles: feature

#95 ✨ [FEAT] 토큰 재발급 api
  README.md
  src/main/java/umc/IRECIPE_Server/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/IRECIPE_Server/controller/MemberController.java
  src/main/java/umc/IRECIPE_Server/converter/MemberConverter.java
  src/main/java/umc/IRECIPE_Server/entity/RefreshToken.java
  src/main/java/umc/IRECIPE_Server/jwt/JwtAuthenticationFilter.java
  src/main/java/umc/IRECIPE_Server/jwt/JwtProvider.java
  src/main/java/umc/IRECIPE_Server/repository/TokenRepository.java
  src/main/java/umc/IRECIPE_Server/service/MemberService.java
Labels: :sparkles: feature

#97 [fix] 프로필 사진 access denied 해결
  src/main/java/umc/IRECIPE_Server/controller/MemberController.java
  src/main/java/umc/IRECIPE_Server/service/MemberService.java
  src/main/java/umc/IRECIPE_Server/service/PostService.java
Labels: :heavy_check_mark: check

#98 main branch merge
  src/main/java/umc/IRECIPE_Server/controller/MemberController.java
  src/main/java/umc/IRECIPE_Server/service/MemberService.java
  src/main/java/umc/IRECIPE_Server/service/PostService.java
Labels: :heavy_check_mark: check

#101 ✨ [FEAT] chatbot 일반 대화
  src/main/java/umc/IRECIPE_Server/controller/ChatGptController.java
  src/main/java/umc/IRECIPE_Server/service/ChatGptService.java
  src/main/java/umc/IRECIPE_Server/service/ChatGptServiceImpl.java
Labels: :sparkles: feature

#102 ✨ [FEAT] 회원 탈퇴API
  src/main/java/umc/IRECIPE_Server/controller/MemberController.java
  src/main/java/umc/IRECIPE_Server/service/MemberService.java
Labels: :sparkles: feature

#104 [fix] 관심글 조회 수정
  src/main/generated/umc/IRECIPE_Server/entity/QMember.java
  src/main/java/umc/IRECIPE_Server/service/MemberService.java
Labels: :heavy_check_mark: check

#107 [FIX] 사용자 관심, 작성글 DTO 수정
  src/main/java/umc/IRECIPE_Server/controller/MemberController.java
  src/main/java/umc/IRECIPE_Server/converter/MemberConverter.java
  src/main/java/umc/IRECIPE_Server/converter/PostConverter.java
  src/main/java/umc/IRECIPE_Server/service/MemberService.java
Labels: :heavy_check_mark: check

#116 ♻️ [Refactor] qna api
  build.gradle
  src/main/generated/umc/IRECIPE_Server/common/QBaseEntity.java
  src/main/generated/umc/IRECIPE_Server/entity/QAllergy.java
  src/main/generated/umc/IRECIPE_Server/entity/QDislikedFood.java
  src/main/generated/umc/IRECIPE_Server/entity/QIngredient.java
  src/main/generated/umc/IRECIPE_Server/entity/QMember.java
  src/main/generated/umc/IRECIPE_Server/entity/QMemberAllergy.java
  src/main/generated/umc/IRECIPE_Server/entity/QMemberLikes.java
  src/main/generated/umc/IRECIPE_Server/entity/QPost.java
  src/main/generated/umc/IRECIPE_Server/entity/QQna.java
  src/main/generated/umc/IRECIPE_Server/entity/QRefreshToken.java
  src/main/generated/umc/IRECIPE_Server/entity/QReview.java
  src/main/generated/umc/IRECIPE_Server/entity/QStoredRecipe.java
  src/main/java/umc/IRECIPE_Server/config/QuerydslConfig.java
  src/main/java/umc/IRECIPE_Server/converter/QnaConverter.java
  src/main/java/umc/IRECIPE_Server/converter/ReviewConverter.java
  src/main/java/umc/IRECIPE_Server/dto/request/QnaRequestDTO.java
  src/main/java/umc/IRECIPE_Server/dto/response/QnaResponseDTO.java
  src/main/java/umc/IRECIPE_Server/dto/response/ReviewResponseDTO.java
  src/main/java/umc/IRECIPE_Server/entity/Qna.java
  src/main/java/umc/IRECIPE_Server/repository/QnaCustomRepository.java
  src/main/java/umc/IRECIPE_Server/repository/QnaRepository.java
  src/main/java/umc/IRECIPE_Server/service/qnaService/QnaServiceImpl.java
Labels: :recycle: refactor

#117 [FIX] 회원 탈퇴, 정보 수정
  src/main/java/umc/IRECIPE_Server/dto/request/MemberRequestDTO.java
  src/main/java/umc/IRECIPE_Server/entity/Member.java
  src/main/java/umc/IRECIPE_Server/entity/Post.java
  src/main/java/umc/IRECIPE_Server/jwt/JwtProvider.java
  src/main/java/umc/IRECIPE_Server/repository/QnaRepository.java
  src/main/java/umc/IRECIPE_Server/repository/ReviewRepository.java
  src/main/java/umc/IRECIPE_Server/repository/StoredRecipeRepository.java
  src/main/java/umc/IRECIPE_Server/service/memberService/MemberService.java
  src/main/java/umc/IRECIPE_Server/service/memberService/MemberServiceImpl.java
Labels: :heavy_check_mark: check
